#' BioTrace workflow scaffolding
#'
#' `use_biotrace()` initialises BioTrace integration in a project by
#' writing `.github/biotrace.yml` and `.github/workflows/biotrace.yml`.
#'
#' `write_biotrace_workflow()` writes the workflow file alone.
#'
#' `biotrace_workflow_text()` returns the workflow file content as a
#' character vector (so callers can inspect or post it without writing
#' to disk).
#'
#' The generated workflow references the upstream Action directly:
#'
#' ```yaml
#' uses: rotsl/biotrace@v1
#' ```
#'
#' It never references this package itself as an Action, because
#' `biotrace` is an R package, not a GitHub Action repository.
#'
#' @section Inputs echoed into the workflow:
#' The generated workflow uses these inputs (matching the upstream
#' `action.yml` of BioTrace v1.x): `config`, `github-token`,
#' `fail-on`, `ai-enabled`. Other inputs retain their upstream
#' defaults. Pass `extra_inputs` to add or override inputs.
#'
#' @param project `[character(1)]` Project root. Defaults to the
#'   current working directory, or the nearest directory containing
#'   `.git` or `DESCRIPTION`.
#' @param config_path `[character(1)]` Path (relative to `project`)
#'   of the BioTrace YAML configuration file. Defaults to
#'   `.github/biotrace.yml`.
#' @param workflow_path `[character(1)]` Path (relative to `project`)
#'   of the GitHub workflow YAML file. Defaults to
#'   `.github/workflows/biotrace.yml`.
#' @param fail_on `[character(1)]` Minimum severity that causes the
#'   Action to fail. One of `"info"`, `"warning"`, `"error"`. Defaults
#'   to `"error"`.
#' @param ai_enabled `[character(1)]` Whether AI observations are
#'   allowed. One of `"auto"`, `"true"`, `"false"`. Defaults to
#'   `"false"` so the workflow is fully deterministic by default.
#' @param include_workflow_dispatch `[logical(1)]` Add a
#'   `workflow_dispatch:` trigger so the workflow can be run
#'   on-demand from the Actions tab. Defaults to `FALSE`.
#' @param upload_report `[logical(1)]` Upload the BioTrace JSON
#'   report as a workflow artifact. Defaults to `TRUE`.
#' @param extra_inputs `[named list]` Extra `with:` inputs to pass
#'   to `rotsl/biotrace@v1`. Each name becomes a YAML key. Use this
#'   to set `create-labels`, `comment-mode`, `report-path`,
#'   `ai-provider`, etc.
#' @param overwrite `[logical(1)]` Overwrite existing files. Defaults
#'   to `FALSE`.
#' @param path `[character(1)]` For [write_biotrace_workflow()], the
#'   path to write. For [biotrace_workflow_text()], ignored.
#'
#' @return
#'   - `use_biotrace()`: a named list of absolute paths
#'     (`config`, `workflow`) invisibly.
#'   - `write_biotrace_workflow()`: the absolute path, invisibly.
#'   - `biotrace_workflow_text()`: a character vector (one element per
#'     line, no trailing newline) representing the workflow YAML.
#'
#' @examples
#' tmp <- tempfile()
#' write_biotrace_workflow(tmp)
#' cat(biotrace_workflow_text(), sep = "\n")
#'
#' @name biotrace_workflow
NULL

# Resolve the project root: prefer the user-supplied one, otherwise
# look for a git root or DESCRIPTION. Fall back to ".".
.resolve_project <- function(project) {
  if (!is.null(project) && nzchar(project)) {
    if (!fs::dir_exists(project)) {
      abort_dir_missing(project)
    }
    return(fs::path_abs(project))
  }
  root <- find_project_root(".")
  if (!is.na(root)) return(root)
  fs::path_abs(".")
}

# Default GitHub workflow snippet that runs upstream BioTrace.
# Generated as a string (not via yaml::as.yaml) so the formatting is
# stable and so reviewers can read it line by line in the diff.
.workflow_template <- function(config_rel, fail_on, ai_enabled,
                               include_workflow_dispatch, upload_report,
                               extra_inputs) {
  if (!fail_on %in% c("info", "warning", "error")) {
    abort_msg(
      paste0("`fail_on` must be one of info, warning, error; got: ", fail_on),
      class = c("biotrace_fail_on_arg", "biotrace_error")
    )
  }
  if (!ai_enabled %in% c("auto", "true", "false")) {
    abort_msg(
      paste0("`ai_enabled` must be one of auto, true, false; got: ", ai_enabled),
      class = c("biotrace_ai_enabled_arg", "biotrace_error")
    )
  }
  if (!is.list(extra_inputs)) extra_inputs <- list()

  # Merge extra inputs over the defaults. We preserve insertion order.
  defaults <- list(
    config = config_rel,
    `github-token` = "${{ github.token }}",
    `fail-on` = fail_on,
    `ai-enabled` = ai_enabled
  )
  inputs <- defaults
  for (nm in names(extra_inputs)) inputs[[nm]] <- extra_inputs[[nm]]

  lines <- character(0)
  add <- function(...) lines <<- c(lines, c(...))

  add("# Generated by the biotrace R package. Do not edit by hand;")
  add("# regenerate with biotrace::use_biotrace().")
  add("name: BioTrace")
  add("")
  add("on:")
  add("  pull_request:")
  add("    types:")
  add("      - opened")
  add("      - synchronize")
  add("      - reopened")
  add("      - ready_for_review")
  if (isTRUE(include_workflow_dispatch)) {
    add("  workflow_dispatch:")
  }
  add("")
  add("permissions:")
  add("  contents: read")
  add("  pull-requests: write")
  add("  issues: write")
  add("  checks: write")
  add("")
  add("jobs:")
  add("  biotrace:")
  add("    runs-on: ubuntu-latest")
  add("    steps:")
  add("      - uses: actions/checkout@v7")
  add("        with:")
  add("          fetch-depth: 0")
  add("")
  add("      - id: biotrace")
  add("        uses: rotsl/biotrace@v1")
  add("        with:")
  for (nm in names(inputs)) {
    val <- inputs[[nm]]
    if (isTRUE(val)) val <- "true"
    if (identical(val, FALSE)) val <- "false"
    # Quote values that YAML would otherwise parse as a boolean / null
    # or that contain expression substitutions. GitHub Actions accepts
    # either form, but quoting matches the upstream workflow style
    # verbatim and avoids ambiguity when the value is "true"/"false".
    if (is.character(val) && length(val) == 1L) {
      val <- .yaml_quote_if_needed(val)
    } else {
      val <- as.character(val)
    }
    add(sprintf("          %s: %s", nm, val))
  }
  if (isTRUE(upload_report)) {
    add("")
    add("      - if: always()")
    add("        uses: actions/upload-artifact@v7")
    add("        with:")
    add("          name: biotrace-report")
    add("          path: ${{ steps.biotrace.outputs.report-path }}")
  }
  add("")
  lines
}

#' @rdname biotrace_workflow
#' @export
biotrace_workflow_text <- function(path = NULL,
                                   config_path = ".github/biotrace.yml",
                                   fail_on = "error",
                                   ai_enabled = "false",
                                   include_workflow_dispatch = FALSE,
                                   upload_report = TRUE,
                                   extra_inputs = list()) {
  # When `path` is supplied and points to a project root, treat
  # `config_path` as relative to it. When NULL, use `config_path`
  # verbatim (callers typically pass a relative path).
  config_rel <- config_path
  if (!is.null(path) && fs::is_absolute_path(config_path)) {
    config_rel <- tryCatch(
      fs::path_rel(config_path, start = path),
      error = function(e) config_path
    )
  }
  .workflow_template(
    config_rel = config_rel,
    fail_on = fail_on,
    ai_enabled = ai_enabled,
    include_workflow_dispatch = include_workflow_dispatch,
    upload_report = upload_report,
    extra_inputs = extra_inputs
  )
}

#' @rdname biotrace_workflow
#' @export
write_biotrace_workflow <- function(path, config_path = ".github/biotrace.yml",
                                    fail_on = "error",
                                    ai_enabled = "false",
                                    include_workflow_dispatch = FALSE,
                                    upload_report = TRUE,
                                    extra_inputs = list(),
                                    overwrite = FALSE) {
  if (!is.character(path) || length(path) != 1L || !nzchar(path)) {
    abort_msg(
      "`path` must be a non-empty single string.",
      class = c("biotrace_path_arg", "biotrace_error")
    )
  }
  if (!is.logical(overwrite) || length(overwrite) != 1L || is.na(overwrite)) {
    abort_msg(
      "`overwrite` must be TRUE or FALSE.",
      class = c("biotrace_overwrite_arg", "biotrace_error")
    )
  }
  if (!overwrite && .exists_file(path)) {
    abort_msg(
      paste0("Refusing to overwrite existing file: ", path,
             ". Pass overwrite = TRUE to replace it."),
      class = c("biotrace_refuse_overwrite", "biotrace_error"),
      path = path
    )
  }

  # The `config:` input that the upstream Action expects is a path
  # relative to the repository root (where `actions/checkout` lands).
  # We do not relativise it against the workflow file's directory:
  # the Action runs from the repo root, not from .github/workflows.
  # If the user passed an absolute path, we try to make it relative
  # to the current working directory so the generated YAML stays
  # portable; otherwise we leave it untouched.
  config_rel <- config_path
  if (fs::is_absolute_path(config_rel)) {
    config_rel <- tryCatch(
      fs::path_rel(config_rel, start = fs::path_abs(".")),
      error = function(e) config_path
    )
  }

  lines <- .workflow_template(
    config_rel = config_rel,
    fail_on = fail_on,
    ai_enabled = ai_enabled,
    include_workflow_dispatch = include_workflow_dispatch,
    upload_report = upload_report,
    extra_inputs = extra_inputs
  )

  # Validate the generated workflow by parsing it back as YAML.
  yaml_text <- paste(lines, collapse = "\n")
  parsed <- tryCatch(
    yaml::yaml.load(yaml_text),
    error = function(e) {
      abort_msg(
        paste0("Internal error: generated workflow is not valid YAML: ",
               conditionMessage(e)),
        class = c("biotrace_internal_yaml", "biotrace_error")
      )
    }
  )
  if (is.null(parsed) ||
      is.null(parsed[["jobs"]]) ||
      is.null(parsed[["jobs"]][["biotrace"]])) {
    abort_msg(
      "Internal error: generated workflow is missing the biotrace job.",
      class = c("biotrace_internal_yaml", "biotrace_error")
    )
  }
  uses <- parsed[["jobs"]][["biotrace"]][["steps"]][[2L]][["uses"]]
  if (!identical(uses, "rotsl/biotrace@v1")) {
    abort_msg(
      paste0("Internal error: generated workflow does not reference ",
             "rotsl/biotrace@v1 (got: ", uses, ")."),
      class = c("biotrace_internal_yaml", "biotrace_error")
    )
  }

  .write_text_utf8(path, lines)
  invisible(as.character(fs::path_abs(path)))
}

#' @rdname biotrace_workflow
#' @export
use_biotrace <- function(project = NULL,
                         config_path = ".github/biotrace.yml",
                         workflow_path = ".github/workflows/biotrace.yml",
                         fail_on = "error",
                         ai_enabled = "false",
                         include_workflow_dispatch = FALSE,
                         upload_report = TRUE,
                         extra_inputs = list(),
                         overwrite = FALSE) {
  root <- .resolve_project(project)
  config_abs <- fs::path_abs(config_path, start = root)
  workflow_abs <- fs::path_abs(workflow_path, start = root)

  # Config first, because the workflow references it. We pass the
  # config_path through verbatim to write_biotrace_workflow because
  # the upstream Action expects a path relative to the repo root
  # (where actions/checkout lands). The default `.github/biotrace.yml`
  # is already in that form.
  write_biotrace_config(config_abs, config = default_biotrace_config(),
                        overwrite = overwrite)

  write_biotrace_workflow(
    path = workflow_abs,
    config_path = config_path,
    fail_on = fail_on,
    ai_enabled = ai_enabled,
    include_workflow_dispatch = include_workflow_dispatch,
    upload_report = upload_report,
    extra_inputs = extra_inputs,
    overwrite = overwrite
  )

  invisible(list(
    config = config_abs,
    workflow = workflow_abs,
    project = root
  ))
}
